{{/*
Secret for notification service credentials
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ .Values.secrets.email.apiKey | quote }}
  fromEmail: {{ .Values.secrets.email.fromEmail | quote }}
