{{/*
ServiceAccount for notification service pods
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "notification.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
